#include "global_optimization.h"
#include <llvm-c/Core.h>
#include <llvm-c/IRReader.h>
#include <llvm-c/Types.h>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <string.h>
#include <string>
#include <stdio.h>